package main

import "fmt"

func main() {
	var score = 6

	switch {
	case score == 8:
		fmt.Println("perfect")
	case (score < 8) && (score > 3):
		fmt.Println("no bad")
		fallthrough
	case score < 5:
		fmt.Println("It is ok, but please study harder")

	default:
		{
			fmt.Println("study harder")
			fmt.Println("You dont have a good score yet")
		}
	}
}

/*
no bad
It is ok, but please study harder



KETIKA KITA INGIN SWITCH PADA BAHASA GO MELANJUTKAN PENGECEKAN KEPADA CASE SELANJUTNYA WALAUPUN SUATU CASE TELAH TERPENUHI KONDISINYA, MAKA KITA BISA MENGGUNAKAN KEYWORD FALLTHROUGH.

JIKA KITA PERHATIKAN PADA GAMBAR DI SEBELAH KANAN, KONDISIONAL SWITCH TERSEBUT AKAN MENGHASILKAN 2 KALIMAT YAITU "NOT BAD" DAN "IT IS OK, BUT YOU NEED TO STUDY HARDER" KARENA KETIKA KONDISI PADA CASE KEDUA TERPENUHI, MAKA DIA PENGECEKAN AKAN BERLANJUT KEPADA CASE KETIGA KARENA CASE KEDUA MENGGUNAKAN  KEYWOARD FALLTHROUGH.const

KETIKA BERLANJUT KE CASE KETIGA, KONDISI NYA TERPENUHI KARENA VARIABLE SCORE MEMILIKI NILAI BERUPA ANGKA 6 DAN ANGKA 6 MEMANG LEBIH BESAR DAIR ANGKA 5.

*/
