package main

import "fmt"

func main() {
	var fruits = [3]string{"apel", "pisang", "mangga"}

	fruits[0] = "apple"
	fruits[1] = "banana"
	fruits[2] = "mango"

	fmt.Printf("%#v\n", fruits)
}

// [3]string{"apple", "banana", "mango"}

/*
PENJELASAN :
ARRAY ( MODIFY ELEMENT THROUGH INDEX)
KITA JUGA DAPAT MEMODIFIKASI ELEMENT-ELEMENT YANG TERDAPAT  DALAM SEBUAH ARRAY DENGAN CARA MENGAKSES INDEXNYA.
CONTOHNYA SEPERTI PADA GAMBAR PERTAMA DISEBELAH KANAN KITA.

TERDAPAT SEBUAH VARIABLE DENGAN NAMA FRUITS YANG MEMILIKI ARRAY YANG ISINYA ADALAH NAMA BUAH-BUAHAN MENGGUNAKAN BAHASA INDONESIA.

LALU BUAH-BUAHAN YANG TERDAPAT PADA ARRAY DALAM VARIABLE FRUITS TERSEBUT DI MODIFIKASI DENGAN CARA MENGAKSES INDEXNYA DAN MENGGANTI BUAH-BUAHAN NYA KEDALAM BAHASA INGGRIS. DAN JIKA DIJALANKAN HASILNYA SEPERTI PADA GAMBAR KEDUA.




*/
