package main

import "fmt"

func main() {
	for i := 1; i <= 10; i++ {
		if i%2 == 1 {
			continue
		}

		if i > 8 {
			break
		}

		fmt.Println("Angka", i)
	}
}

/*

Angka 2
Angka 4
Angka 6
Angka 8


PENJELASAN :

SEBELUMNYA KITA TELAH MENERAPKAN KEYWORD BREAK UNTUK MENGHENTIKAN SEBUAH PROSES LOOPING, DAN SEKARANG KITA JUGA AKAN MEMAKAI KEYWORD CONTINUE YANG DIGUNAKAN UNTUK MELANJUTKAN SUATU PROSES LOOPING.
CONTOHNYA SEPERTI PADA GAMBAR PERTAMA DIBAWAH INI --->


PADA LOOPING DIBAWAH, TERDAPAT 2 KONDISIONAL YANG DIMANA PADA KONDISIONAL PERTAMA DIGUNAKAN UNTUK MEMERIKSA JIKA VAIRABLE i MEMILIKI NILAI GANJIL, MAKA PROSES LOOPING NYA DIPAKSA BERLANJUT DAN AKAN MENGACUHKAN SYNTAX YANG ADA DIBAWAH KEYBOARD CONTINE (PADA KASUS KITA SEKARANG BERARTI KONDISIONAL KEDUA DAN FUNGSI fmt.Println PADA LOOPING DIBAWAH )

LALU PADA KONDISIONAL KEDUA DIGUNAKAN UNTUK MEMERIKSA JIKA BARIABLE i SUDAH MEMILIKI NILAI DIATAS ANGKA 8, MAKA KEYWORD BREAK AKAN TERPANGGIL DAN PROSES LOOPING AKAN BERGENTI. JIKA KITA JALANKAN PADA TERMINAL KITA, MAKA HASILNYA AKAN SEPERTI PADA GAMBAR KEDUA DIBAWAH INI

*/
